import localFont from "next/font/local";
import "./globals.css";
import '@mantine/core/styles.css';

import React from 'react';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import { CollapseDesktop } from "../components/CollapseDesktop";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MantineProvider withGlobalStyles withNormalizeCSS>
          <div style={{ backgroundColor: "#17171e", minHeight: "100vh" }}>
            <CollapseDesktop>
              {children}
            </CollapseDesktop>
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
